name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run frontend unit tests
      working-directory: ./frontend
      run: npm test

    - name: Run backend unit tests
      working-directory: ./backend
      run: npm test

    - name: Merge dev to main
      if: success()
      uses: "pascalgn/automerge-action@v0.14.3"
      with:
        target_branch: main
        branch: dev
        commit_message: "Automated merge from dev to main"
