name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run frontend unit tests
      working-directory: ./frontend
      run: npm test

    - name: Run backend unit tests
      working-directory: ./backend
      run: npm test

    - name: Build Docker images
      run: docker-compose build

    - name: Push Docker images
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker-compose push
